version: "3"

services:
  myapp:
    image: myapp:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: overlay
